import './about.css.proxy.js';
/* src\components\about.svelte generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	attr,
	detach,
	element,
	init,
	insert,
	listen,
	noop,
	run_all,
	safe_not_equal,
	space
} from "../../web_modules/svelte/internal.js";

function create_else_block(ctx) {
	let p;

	return {
		c() {
			p = element("p");
			p.textContent = "about";
		},
		m(target, anchor) {
			insert(target, p, anchor);
		},
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

// (38:2) {#if mouseover}
function create_if_block(ctx) {
	let p0;
	let t3;
	let p1;
	let t7;
	let p2;
	let t9;
	let p3;

	return {
		c() {
			p0 = element("p");

			p0.innerHTML = `This photo album website was made using
      <a href="https://svelte.dev/" class="svelte-s0p7u1">svelte</a>
      front-end javascript framework.`;

			t3 = space();
			p1 = element("p");

			p1.innerHTML = `Source code is available at
      <a href="https://github.com/shibii/photo-album/tree/master" class="svelte-s0p7u1">github</a>.`;

			t7 = space();
			p2 = element("p");
			p2.textContent = "All presented photographs have been taken by Seppo Kilpeläinen.";
			t9 = space();
			p3 = element("p");

			p3.innerHTML = `Gear and software: Canon EOS 600D camera with kit lens, edited in
      <a href="https://www.darktable.org/" class="svelte-s0p7u1">darktable</a>.`;

			attr(p0, "class", "svelte-s0p7u1");
			attr(p1, "class", "svelte-s0p7u1");
			attr(p2, "class", "svelte-s0p7u1");
			attr(p3, "class", "svelte-s0p7u1");
		},
		m(target, anchor) {
			insert(target, p0, anchor);
			insert(target, t3, anchor);
			insert(target, p1, anchor);
			insert(target, t7, anchor);
			insert(target, p2, anchor);
			insert(target, t9, anchor);
			insert(target, p3, anchor);
		},
		d(detaching) {
			if (detaching) detach(p0);
			if (detaching) detach(t3);
			if (detaching) detach(p1);
			if (detaching) detach(t7);
			if (detaching) detach(p2);
			if (detaching) detach(t9);
			if (detaching) detach(p3);
		}
	};
}

function create_fragment(ctx) {
	let div;
	let mounted;
	let dispose;

	function select_block_type(ctx, dirty) {
		if (/*mouseover*/ ctx[0]) return create_if_block;
		return create_else_block;
	}

	let current_block_type = select_block_type(ctx, -1);
	let if_block = current_block_type(ctx);

	return {
		c() {
			div = element("div");
			if_block.c();
			attr(div, "class", "hoverable svelte-s0p7u1");
		},
		m(target, anchor) {
			insert(target, div, anchor);
			if_block.m(div, null);

			if (!mounted) {
				dispose = [
					listen(div, "mouseenter", /*mouseenter*/ ctx[1]),
					listen(div, "mouseleave", /*mouseleave*/ ctx[2])
				];

				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (current_block_type !== (current_block_type = select_block_type(ctx, dirty))) {
				if_block.d(1);
				if_block = current_block_type(ctx);

				if (if_block) {
					if_block.c();
					if_block.m(div, null);
				}
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div);
			if_block.d();
			mounted = false;
			run_all(dispose);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let mouseover = false;

	const mouseenter = () => {
		$$invalidate(0, mouseover = true);
	};

	const mouseleave = () => {
		$$invalidate(0, mouseover = false);
	};

	return [mouseover, mouseenter, mouseleave];
}

class About extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default About;